blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

#facebook_login:
#    path: /login/check-facebook
#
google_login:
    path: /login/check-google
#
#github_login:
#    path: /login/check-github

vkontakte_login:
    path: /login/check-vkontakte

logout:
    path:   /logout

foggyline_ticker:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /
