## To get started with security, check out the documentation:
## http://symfony.com/doc/current/book/security.html
#security:
#
#    acl:
#        connection: default
#    encoders:
#        Blogger\BlogBundle\Entity\User:
#            algorithm:        sha1
#            encode_as_base64: false
#            iterations:       1
#
#    role_hierarchy:
#        ROLE_USER:       ROLE_USER
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
#
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        my_custom_hwi_provider:
#            id: ib_user.oauth_user_provider
#
#    firewalls:
#        main:
#            pattern: ^/
#            anonymous: true
#            logout: true
#            logout:
#                path:   /logout
#                target: /
#            oauth:
#                resource_owners:
#                    check_path: /login_check
#                    vkontakte: /login/check-vkontakte
#                    login_path: /login
#                    failure_path: /login
#                    oauth_user_provider: ib_user.oauth_user_provider
#                login_path: /login
#                oauth_user_provider:
#                    service: ib_user.oauth_user_provider
#
##        access_control:
##            - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
##            - { path: ^/presence, roles: ROLE_ADMIN }
##            - { path: ^/user, roles: ROLE_USER }

security:
    providers:
        ib_user.oauth_user_provider:
            id: ib_user.oauth_user_provider

    firewalls:
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                    oauth_user_provider: ib_user.oauth_user_provider
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: ib_user.oauth_user_provider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }